# Generated by Django 4.2.11 on 2024-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trains',
            fields=[
                ('trainId', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('plan', models.IntegerField()),
            ],
        ),
    ]
