# Generated by Django 4.2.11 on 2024-03-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_trains_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trains',
        ),
    ]
